### ISSUE TITLE
Better doc for file task

### ISSUE THREAD

**Issue by ghost** [jakejs/jake#151]
There are some question marks left after reading about the file task.

Eg.
1. I could process the concatenated content in the handler, but how?
2. It says that the file should exist. But how could it exist if it's the first time I create it?
3. How do I run the task.

Here is an example:

```
file('production.js', ['app/javascripts/app.js', 'app/javascripts/data.js'], function (params) {
  console.log('done');
});
```

I run `jake production.js` but nothing happens.

Questions like these shouldn't arise! Would be great if this could be clarified in the doc.

**Comment by tinganho** [comment]
Just took me 3 hours to find the problem—that I need put a dependency in order for the file task to execute. :cry:

**Comment by mde** [comment]
Would love a PR that improves the doc for this.

**Comment by cbowdon** [comment]
I was just banging my head against the same issue. Things I fell over on:

* jake.exec is asynchronous so my file task needs async:true and to call complete
* If the task does not actually create the file (e.g. because you've just stubbed it) the task will fail

jake.exec being asynchronous is reasonably well signposted, it's more the latter that was the problem for me because when I was struggling, I tried the examples without filling in the blanks and was confused when they didn't work:

    file('foo-minified.js', ['bar', 'foo-bar.js', 'foo-baz.js'], function () {
        // Code to concat and minify goes here
        // Except I just put 'console.log' because I didn't expect it to fall over if file not actually produced
    });

Full stack trace was:

    Error: ENOENT, no such file or directory 'foo-minified.js'
    at Object.fs.statSync (fs.js:689:18)
    at FileBase.updateModTime (/usr/local/lib/node_modules/jake/lib/task/file_task.js:82:20)
    at FileBase.complete (/usr/local/lib/node_modules/jake/lib/task/file_task.js:89:12)
    at TaskBase.run (/usr/local/lib/node_modules/jake/lib/task/task.js:277:12)
    at TaskBase.handlePrereqComplete (/usr/local/lib/node_modules/jake/lib/task/task.js:229:12)
    at null.<anonymous> (/usr/local/lib/node_modules/jake/lib/task/task.js:189:16)
    at g (events.js:180:16)
    at EventEmitter.emit (events.js:92:17)
    at FileBase.complete (/usr/local/lib/node_modules/jake/lib/task/file_task.js:93:10)
    at TaskBase.run (/usr/local/lib/node_modules/jake/lib/task/task.js:277:12)

Either an addition to the docs or a more specific error message would have helped here.

**Comment by mde** [comment]
The docs are in the repo. Please fix the docs in a way you think is good, and give us a PR.

**Comment by markalanevans** [comment]
how do you specify the directory where the file should be built to?

**Comment by mde** [comment]
Everything is relative to the currently running process.

**Comment by albertjin** [comment]
After reading this thread, I've got an idea about how to use `file` and `jake.exec` properly.  Here goes an example.

```javascript
desc('demo for file task');
file('a.out', ['a1.in', 'a2.in'], async () => {
    return new Promise((resolve) => {
        jake.exec('cat a1.in a2.in > a.out', {}, () => {
            resolve();
        });
    });
});
```

**Comment by mde** [comment]
I wouldn't be using `jake.exec` anymore. It was used to make the async `exec` more palatable, but now we have `execSync`. The vast majority of shell commands can be run with that now.
