### ISSUE TITLE
Output is ugly with Stdout/err w/ jake.exec

### ISSUE THREAD

**Issue by OscarGodson** [jakejs/jake#216]
For example, if I were to do `npm install` the out put would look like:

```
npm
 http 304 https://registry.npmjs.org/qs/0.6.5
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm
http 304 https://registry.npmjs.org/send/0.1.1
npm
 WARN package.json forever-agent@0.2.0 No README.md file found!
```

I'd like the keep the output as is if I were to run these manually in my terminal. I lose color and formatting using `jake.exec`.

**Comment by welearnednothing** [comment]
If you pass `printStdout: true` and `printStderr: true` into your `jake.exec` options, you'll have colors in your output.

```javascript
task('npmColors', function() {
   var e = jake.exec('npm install utilities', {printStdout: true, printStderr: true},  function() {
     complete();
   });
 }, {async: true});
```
