### ISSUE TITLE
How to attach debugger

### ISSUE THREAD

**Issue by MichaelPaulukonis** [jakejs/jake#226]
How can I attach the debugger to a jake process?

Specifically, I'm trying to use node-inspector, but since that requires an already-running-node-process (and my jakefile tasks don't take that long) or a node-process started with debug-break (say `node --debug-brk <file.js>`)...

Unless I add in some jiggery-pokery to cause a task to wait for console input, how can this be done?

**Comment by virtualpatterns** [comment]
Thanks!

**Comment by sergeyblohin** [comment]
Thanks, work for me!
