### ISSUE TITLE
jakelib without Jakefile

### ISSUE THREAD

**Issue by jupl** [jakejs/jake#233]
I wrote a set of tasks under the `jakelib` directory. If I try to run `jake` I get an error saying that I don't have a `Jakefile`. I solved this by adding a blank `Jakefile`, which is nice but adds an unnecessary file to the project. It would be nice to not have to add `Jakefile` if I all I need is `jakelib`.

**Comment by welearnednothing** [comment]
It looks like this may have been fixed by b0fcf1cd80fff6dac7d9eecf4524eae66c0ca50c back in 0.7.8.

**Comment by mde** [comment]
:+1: Closing this issue.
