### ISSUE TITLE
Include .jake files from a submodule

### ISSUE THREAD

**Issue by joshleaves** [jakejs/jake#234]
I'm building a Node.js micro-framework and wanted to add a "rake routes"-like utility using Jake. Unfortunately, such a script would have to be included within my module.

Having to use a script or any other binary to include it in jakelib from somewhere else would just be counter-productive to the "micro-framework". I built a quick test to see if jake would check the node_modules subfolder in search of jakefiles:

```
 testjake $ tree
.
├── Jakefile
├── jakelib
│   └── libs.jake
└── node_modules
    └── another_lib
        └── jakelib
            └── other_libs.jake

4 directories, 3 files
testjake $
```

Here is the current behaviour:

```
testjake $ jake -T
jake default            # Jakefile: Default task
jake libsfunction       # jakelib/libs.jake: Default task
testjake $
```

Nope, no such luck :) And I don't want to add manually the jakelib for all folders I may need everytime I type "jake".

So the proposed behaviour for this new feature would be the following:

```
testjake $ jake -T
jake default                      # Jakefile: Default task
jake libsfunction                 # jakelib/libs.jake: Lib task
jake another_module:default       # Jakefile: Default task (from module another_module)
jake another_module:libsfunction  # jakelibs/libs.jake: Lib task (from module another_module)
testjake $
```

Of course, to avoid method overwrite by modules, all modules tasks are namespaced to the module name.

Some discussion about this feature before I start diving in it:
- I propose the -R command-line argument switch to activate the Recursive search to all node_modules folders.
- If commands from other modules become namespaced, some cross-invocation may fail. The best practice I have in mind right now would be to namespace both task names and task dependencies: each module's namespace gets sandboxed and can't reach the outside world.
- Some tasks defined for a library may not be meant to be used outside of their context. Using a `{ inheritable: false }` option parameter (defaults to `true`) to mark such tasks would be a good compromise.

What do you think?

**Comment by navneetgarg123** [comment]
It would probably make more sense to just add a require line into the `Jakefile` to load the tasks that would programmatically the load the tasks for that module. 

How we do that is up to debate.
*  We could make the calling module establish how it loads its tasks.
```js
//Jakefile
require('micro-framework').loadJakeTasks()
```
* `jake` provides its own interface for loading tasks from a module
```js
//Jakefile
jake.loadTasks('micro-framework')
```

Either way the objective would be to load all of the tasks defined for that project. However, the first option puts the onus on the calling module to define its namespace. The second option could put the onus on either jake or the calling module.

**Comment by navneetgarg123** [comment]
I've pushed up a possible implementation of this for
* requiring tasks from a local directory/installed module
* recursively requiring tasks from a directory

It hasn't been wired up with the command line yet thought.
I've linked the commits below

[sub module require](https://github.com/navneetgarg123/jake/commit/c2adf5e4abfba99b419e10234ad7e1a7dbc44202)
[recursive require](https://github.com/navneetgarg123/jake/commit/bc760ce2bb4dc2d70c35bdcf71a1a41f3b6586a4)

**Comment by joshleaves** [comment]
Stale :)
