### ISSUE TITLE
Check also for "jakefile" (lowercase)

### ISSUE THREAD

**Issue by adius** [jakejs/jake#253]
I just had this nasty bug where my jakefile was named "jakefile" instead of "Jakefile".
I'm developing on a mac so this wasn't a problem as the mac file system is case-insensitive. However, when I wanted to run my tests with travis I always got an error message because jake couldn't find a jakefile as travis tests are running on linux, which is case-sensitive.
So I think you should check also check for a lowercase "jakefile"!
What do you think?

**Comment by welearnednothing** [comment]
Confirmed fixed in 2dc2b59
