### ISSUE TITLE
async task not calling 'complete'

### ISSUE THREAD

**Issue by raeesaa** [jakejs/jake#271]
Hi,

I have defined an async task in Jakefile as:

```
task('save', {async: true}, function () {
    var funders = someFunction();

    MongoClient.connect(config.development.dbUrl, function(err, db) {
      if (!err) {
        db.collection("somecollection").insert({date: new Date(), funders: funders}, function(err, doc) {
          if(err)
            console.log(err);

          console.log('Data inserted');
          complete();
        });
      }
    });
  });

```
Task get executed fine and I can see 'Data inserted' logged into the console. But `complete()` is not getting called due to some reason. I am stuck with this task since past four hours. Any idea why complete is not getting invoked?

**Comment by mtimofiiv** [comment]
I have the exact same issue, also with modifying a mongo record.

Like @raeesaa, the task executes fine but then the process does not exit. Here's my `Jakefile`:
https://gist.github.com/mtimofiiv/33a521b5b7c9f301d047

**Comment by mtimofiiv** [comment]
I think I fixed this for myself - there's a bit right in the docs. Tasks marked as `{ async: true }`, including ones that are not inherently marked as so but make use of something like promises/callbacks (as in the case of my tasks that run an asynchronous Mongo query) just need this event listener somewhere in the Jakefile:

```javascript
jake.addListener('complete', function () {
  process.exit();
});
```

source: http://jakejs.com/docs#tasks_cleanup_after_all_tasks_run,_jake_'complete'_event

**Comment by mde** [comment]
Glad you were able to get this sorted out. :) @raeesaa, is this still an issue for you?

**Comment by siimsoni** [comment]
It seems like it is a common error that tasks don't get terminated. I highly recommend to rethink this part of Jake or to come up with some guide how to resolve these issues… I'm even having issues to the extent that the process gets terminated one time and at another time I can even delete everything from the task, all of the tasks get executed but the last one keeps hanging… I'm not very proficient with Node, but I can say I am very confused now.

**Comment by mde** [comment]
This is not a Jake problem, it's a problem in your application code or a third-party library. If you open connections and don't close them, or call out to libraries that don't clean up after themselves, the Node process will continue running. Jake has already exited.

Jake does itself give you a 'complete' event you can listen for that tells you when all tasks have finished running:

http://jakejs.com/docs#tasks_cleanup_after_all_tasks_run,_jake_%27complete%27_event
