### ISSUE TITLE
How to know that all stdout was read

### ISSUE THREAD

**Issue by Aetet** [jakejs/jake#283]
In my program I use jake.exec, but it output wrong results for stdout. AFAIK jake.exec using child_process.spawn under the hood, but there's no any 'end' event for stdout stream. How can be sure that all stdout was read?

**Comment by welearnednothing** [comment]
@Aetet Can you post your code? The returned `Exec` instance does emit an `end` event which is triggered by an `exit` event from `child_process.spawn`.

**Comment by Aetet** [comment]
It is not relevant yet. We abandon jake and replace it with gulp.
