### ISSUE TITLE
Why are jake methods exposed globally

### ISSUE THREAD

**Issue by danny-andrews** [jakejs/jake#316]
What was the rationale behind exposing the main jake methods (e.g. `desc`, `task`, `namespace`) globally? It's a bit frustrating to have to add a linter annotation for all of them, and it runs the risk of collisions. This is a mistake mocha made which I think has hurt its adoption.

**Comment by zen-mde** [comment]
I started building Jake around Node v0.2. Node was still pretty new and experimental, and I just wanted something to build my own projects without having to install Ruby. It originally was just a port of Rake, so I did most things the same way Rake did.

I would not be opposed to a major version bump that actually removes them from the global.

**Comment by mde** [comment]
I started building Jake around Node v0.2. Node was still pretty new and experimental, and I just wanted something to build my own projects without having to install Ruby. It originally was just a port of Rake, so I did most things the same way Rake did.

I would not be opposed to a major version bump that actually removes them from the global.
