### ISSUE TITLE
packageTask dependency

### ISSUE THREAD

**Issue by reshadi** [jakejs/jake#323]
Hi,

From the code, it looks like the TestTask and PackageTask classes are very similar. The PackageTastk constructor does accept prereqs, but the packageTask() function does not pass the dependencies to the constructor.

As simple fix (in lib/api.js) is like this:
this.packageTask = function (name, version, prereqs, definition) {
    return new jake.PackageTask(name, version, prereqs, definition);
};

Or the same pattern that testTask is using can be used for creating the package task. I think this model is actually more preferred and maintainable.

Thanks.

**Comment by badquanta** [comment]
Just started using Jake and noticed this too.  Perhaps the intent is for us to .invoke other tasks within this one? 

Am I supposed to do something like:
`this.packageFiles.toArray().forEach(file => {
        if (jake.Task[file]) this.prereqs.push(file);
});`

**Comment by mde** [comment]
Looks like the constructor correctly handles the prereqs arg as optional, so there's no harm in passing it from the `packageTask` API method. I'll make that change.

**Comment by mde** [comment]
Changed and published to NPM, v8.1.1.
