### ISSUE TITLE
The .file export is inconsistent

### ISSUE THREAD

**Issue by vp2177** [jakejs/jake#326]
const { task } = require('jake')
    task('foo', () => console.log('PASS'))

vs.

    const { file } = require('jake')
    file('foo.min.js', [ 'file.js' ], () => console.log('FAIL'))

**Comment by mde** [comment]
What module system is this? It looks like a semicolonless mix of native ES imports and CommonJS.

**Comment by vp2177** [comment]
It's a Jakefile.
As those are interpreted in Node, it's CommonJS (no ES `import`s, yet).

Issue is regardless of module system however.

**Comment by mde** [comment]
Fixed in 80457ee5c45d171621cdb46945752cf1801cfe4e and pushed to NPM, v8.0.15.

**Comment by vp2177** [comment]
Verified fixed, thank you

**Comment by mde** [comment]
You're very welcome, and thank you for reporting it. Apologies for the confusion about the import statement -- my friend @MiguelMadero pointed out to me that it's just simple object destructuring assignment. Apparently I am getting old, and it takes me a while to recognize all the newish ES6 syntax when I see it. :)
