### ISSUE TITLE
Ability to set max_old_space_size

### ISSUE THREAD

**Issue by pshegde** [jakejs/jake#328]
Is there some way to specify the memory this jake task can use? Something like the max_old_space_size. I keep running into the following error with my jake task:

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->

1440983 ms: Scavenge 1410.7 (1462.0) -> 1410.7 (1462.0) MB, 0.1 / 0 ms (+ 1.8 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
1441102 ms: Mark-sweep 1410.7 (1462.0) -> 1368.7 (1455.3) MB, 119.2 / 0 ms (+ 2.1 ms in 2 steps since start of marking, biggest step 1.8 ms) [last resort gc].
1441231 ms: Mark-sweep 1368.7 (1455.3) -> 1368.7 (1455.3) MB, 129.0 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x359384dd81b1 <JS Object>
    1: ToString(aka ToString) [native runtime.js:~453] [pc=0x27fa7feb37d] (this=0x359384d04189 <undefined>,h=1130114)

**Comment by busticated** [comment]
i ran into this a while back and [ended up just fork'ing my process](https://github.com/karma-runner/karma/issues/1868#issuecomment-180027452). it's been working fine so far.

**Comment by pshegde** [comment]
Thanks for the link. I decided to use gulp since that worked easily for me.
