### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jacobweber** [jakejs/jake#363]
Hi. Is there a list of what's changed in recent versions? The [changelog.md](https://github.com/jakejs/jake/blob/master/changelog.md) file doesn't have anything since 0.7.

**Comment by mde** [comment]
There's a major version bump. I moved it to 10, since there's a lot that is different. I'll update the changelog ASAP.

**Comment by mde** [comment]
I've updated the changelog on master: https://github.com/jakejs/jake/blob/master/changelog.md

The basic gist of it is, I've added support for generic exported functions as tasks in Jakefile, and an experimental `series` function for composing tasks:

```javascript
async function foo() {}
async function bar() {}

exports.foo = foo;
exports.baz = series(foo, bar);
```
I'll be updating docs as I have time, but I would love some help if anybody's interested. :)

**Comment by jacobweber** [comment]
Cool, thanks!

**Comment by esamattis** [comment]
I'd recommend to use use [np][] for releases. It automatically does tags and npm publish but must importantly it will open the Github release form with prefilled list of commits in that release which is very easy to clean up for more human readable changelog. 

Here's an example of immer-reducer releases page https://github.com/esamattis/immer-reducer/releases

[np]: https://www.npmjs.com/package/np

**Comment by mde** [comment]
This looks great. However NP seems to have a lot of overlap with Jake's PublishTask, which is what I have used since the very early days of Jake to manage releases.

This looks like a great opportunity to integrate it with GitHub's API, and just create releases automatically.

**Comment by jacobweber** [comment]
Hi again. Looks like it's getting a little out of date. For example, I'm noticing a new timeout of 30sec that doesn't seem to be documented, somewhere version 10.0.6 and the current version.
