### ISSUE TITLE
Cannot find module 'jake'. WHHAATT!?

### ISSUE THREAD

**Issue by yilmazdurmaz** [jakejs/jake#394]
pre-note for future use: If you have this issue now or in the future, it is possible you missed some points in documentation, or they haven't yet been edited yet after discussions in this issue. then please read discussions here for descriptions of causes and solutions.
---

when you can't even follow some documentation from one tool's own page, there is something big to fix. the only working thing if ``jake -h`` and ``jake -v`` to give version number :``10.8.2``

to reproduce:

install globally ``$ npm install -g jake``

then make a ``jakefile.js``, actually copy/paste the ``Sample Jakefile`` from [docs](https://jakejs.com/docs-page.html).

then try ``jake``, or ``jake -T``, or ``jake -t``, or ``npx jake``. all fails just because of this module error.

````
jake aborted.
Error: Cannot find module 'jake'
Require stack:
- C:\WorkSpace\Vue\jakefile.js
- C:\Users\durmaz\AppData\Roaming\npm\node_modules\jake\lib\loader.js
- C:\Users\durmaz\AppData\Roaming\npm\node_modules\jake\lib\jake.js
- C:\Users\durmaz\AppData\Roaming\npm\node_modules\jake\bin\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)      
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\WorkSpace\Vue\jakefile.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)        
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
````

**Comment by welearnednothing** [comment]
@yilmazdurmaz I can imagine your frustration here. Likewise, it's frustrating for all of the contributors of Jake to see such a problem, given all of the thankless hard work @mde and many others have put into it - especially when a script that might have once worked reliably is now failing for and discouraging a new user. Let's try to keep the dialog here respectful to @mde, the other contributors, and the Jake community.

## Short Answer
Install Jake locally in your project (which is suggested immediately after the global install)
```
npm install --save-dev jake
```

Hopefully that solves the problem! If not, let us know and someone can try to help debug.

## More Detail
The gist of it is, standards of Node have shifted over time and at one point you would have had your global node_modules searched within your dependency chain when running a global install of Jake (or any lib). That's no longer the case as it can lead to unpredictable results within projects (the age old dictum that global variables are bad applies here). [The Node docs](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) dive into this a bit more.

Note that this will still work with the global install for folks that have their global node_modules in their NODE_PATH environment variable - so this won't universally fail for everyone. That said, it's no longer best practice to do so.

You can find a similar issue discussed [here](https://stackoverflow.com/questions/12594541/npm-global-install-cannot-find-module).

@mde perhaps it's time to remove the suggestion to install globally and just push everyone in the direction of a local install these days. That's likely more inline with what people are used to in the Node world these days (and for good reason).

**Comment by mde** [comment]
This is a Windows-only bug. Definitely worth fixing, but Windows CLI tools have always been a maintenance issue with Node-based CLI tools. I'll take a look at this sometime this weekend. And thanks for the request for civility, @welearnednothing. It's really appreciated.

**Comment by welearnednothing** [comment]
Yeah, of course @mde. I was able to reproduce this on **macOS 10.15.7**, actually. My NODE_PATH env var was empty and it failed exactly as described. Adding my global node_modules to NODE_PATH worked as expected. This machine has been around the block a few times, so I don't know what happens on a clean Node install - but I suspect it's not to set a NODE_PATH anymore.

**Comment by mde** [comment]
Ah, that is super helpful. We can easily add that to the docs for 'Nix installs, but I'm not sure what will be needed for Windows. I'll have to dig up a Win VM to test this on.

**Comment by yilmazdurmaz** [comment]
@welearnednothing 
that discussion on stackoverflow was started almost 10 years ago. it is amazing to have this kind of a problem even years after.

**Comment by yilmazdurmaz** [comment]
@mde 
If it helps I tried the following.

with my already globally installed version, I used ``npm install --save-dev jake`` in an empty folder and just created a single jakefile with sample code in it (no project needed).

invoking ``jake`` command directly now works fine, and uses newly created ``node_modules`` folder inside working directory. 

I did not set a path to ``bin`` folder in this local module folder, and also renamed "bin" folder to be sure jake is not started from within this folder, so safe to say the globally installed jake is running.

and the result is apparent that even a global installation of jake looks for this local "save-dev" folder right now.

**Comment by yilmazdurmaz** [comment]
I was confused about this module path thing. now I begin to understand the possibilities here.

besides things you mentioned, it is possibly worth mentioning about module path somewhere in between lines.

you may include an explanation, for example, or redirect to a discussion like this one I have found similar/same: [Nodejs cannot find installed module on Windows](https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows) (this one being about "jade" is incidental :) )

as we now have a discussed issue at hand with useful suggested solutions in it, you can mark this issue as solved and close anytime you see fit.
