### ISSUE TITLE
When can we see the latest version of jakejs published to NPM ? 

### ISSUE THREAD

**Issue by pankajanand18** [jakejs/jake#399]
Hello,

I would like to know what it takes to publish the latest release from github to npm ? 
There are couple of changes in the latest build that we would like to take :-) . I see the last version was published a year ago. 

Thanks in advance.

**Comment by ericcornelissen** [comment]
@busticated @myconode pinging you as owners of [the jakejs GitHub organisation](https://github.com/jakejs), do you have an update on the status of this project?

**Comment by mde** [comment]
I've just published current HEAD as `v10.8.3.` Thank you for your patience!
