### ISSUE TITLE
Error `Cannot read property '1' of null` when running `jake -T`

### ISSUE THREAD

**Issue by mgrandrath** [jakejs/jake#405]
After upgrading to v10.8.4 I received the error message `Cannot read property '1' of null` when running `jake -T`. I could trace back the error to [this line](https://github.com/jakejs/jake/blob/4684134346fab13d1e1bc7f77f8ee4fb838a8850/lib/task/task.js#L423) introduced in d39f72d.

The problem seems to be that the regex does not match [this action](https://github.com/jakejs/jake/blob/4684134346fab13d1e1bc7f77f8ee4fb838a8850/lib/jake.js#L218) in `jake.js`. The issue can be fixed by providing a name to the function:
```javascript
…
case 'directory':
  action = function action () { // <-- add name `action` here
    jake.mkdirP(name);
  };
  task = new DirectoryTask(name, prereqs, action, opts);
  break;
…
```

**Comment by falsefalse** [comment]
[Related](https://github.com/jakejs/jake/commit/3bff4da67e01b98db04a6ab6507891b7140c84dd)

**Comment by mde** [comment]
Does that other PR fix this problem, or no?

**Comment by falsefalse** [comment]
Yes it does

**Comment by mde** [comment]
Awesome, thank you!
