### ISSUE TITLE
Jake fails to properly use environment variables passed as arguments when value contains equal sign

### ISSUE THREAD

**Issue by yentlprojects** [jakejs/jake#422]
When passing arguments to Jake using the environment variables syntax, it breaks when a value contains an equal sign:

Say we have the following task:
```js
task('test', function () {
    console.log("extra_arg_string:", process.env.extra_arg_string);
});
```

Which we invoke as follows:
```bash
jake test extra_arg_string="-Ddb.username=my-db-user -Ddb.password=my-password"
```

The process.env variable stops right before the first equals sign in the value:
```js
extra_arg_string: -Ddb.username
```

Escaping equals sign with backslashes also does not seem to work.

**Comment by mde** [comment]
This looks like a valid bug, although an easy workaround would be simply to pass two different environment variables, one for `Ddb.username` and `Ddb.password`, so this doesn't seem like a really high priority to fix.

**Comment by yentlprojects** [comment]
In understand this might not be high priority to fix, but in our use case it isn't really possible to just pass 2 environment variables, because this heavily limits the reusability of the script, as this "extra_arg_string" command gets passed through to a maven build inside a docker container. 
The goal is for the jake script to accept any amount of env vars/system properties and pipe those through to the docker build.

**Comment by mde** [comment]
Another possibility would be simply to set env variables before invocation, like so:

```bash
EXTRA_ARG_STRING="-Ddb.username=my-db-user -Ddb.password=my-password" jake test`
```

Another way to set an env variable for your tasks would be to `require` a file in your jakefile that sets them for you:

```javascript
process.env.EXTRA_ARG_STRING = 'Ddb.username=my-db-user -Ddb.password=my-password';
```

That "equals" syntax was originally implemented simply to copy all of Rake's API. There's no specific reason to set environment variables that way.

Hope that helps.

**Comment by mde** [comment]
I would add, that "equals" syntax actually sets full-blown environment variables. If you're just wanting to pass args through the Jake task, you'd be better served by just passing args:

https://jakejs.com/docs-page.html#item-advanced-usage-passing-parameters
