### ISSUE TITLE
--tasks print source code of jakefile.js

### ISSUE THREAD

**Issue by tit** [jakejs/jake#427]
Hi, sorry for my bad English.

Previously, `--tasks` returned only a list of tasks (expected). 
Now it began to return the source code of the entire file. 
Why?

```shell
cat jakefile.js
```
↓
```javascript
const Jake = require('jake')

Jake.desc('Playground')
Jake.task('playground', () => {
  console.log('playground')
})
```

```shell
jake --tasks
```
↓
```shell
 () => {
  console.log('playground')
}

 () => {
  console.log('playground')
}

jake playground   # Playground
```

Jake version: 10.8.6

**Comment by mde** [comment]
Fixed and pushed to NPM in v10.8.7. Thank you so much for reporting this!
