### ISSUE TITLE
best way to execute shell commands and preserve color

### ISSUE THREAD

**Issue by prabirshrestha** [jakejs/jake#79]
I want to execute a shell command in windows using cmd.

	var spawn = require('child_process').spawn,
		cmd    = spawn('cmd', ['/s', '/c', 'C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\MSBuild c:\\test.sln']);

	cmd.stdout.on('data', function(data){
		process.stdout.write(data);
	});

	cmd.stderr.on('data', function(data){
		process.stderr.write(data);
	});

	cmd.on('exit', function(code){
		console.log(code);
	});

The problem is the color is not preserved. Rather it uses default color. 

Any idea how to redirect the stdout and preserve the color.

Here is the original question I posted in stackoverflow. http://stackoverflow.com/questions/7725809/preserve-color-when-executing-child-process-spawn

**Comment by tinganho** [comment]
Any fix on this?

**Comment by mde** [comment]
Pushed to NPM in f1d655515d54788183fbf89617a8fea351e2313f
